
name: Frontend Local CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull frontend code
        run: |
          cd ~/ci/app/apptraining-2-front
          git pull

      - name: Rebuild frontend
        run: |
          cd ~/ci/app
          docker compose up --build -d frontend
